---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: install.yml
  tags:
    - system
    - networking
    - ssh
    - ssh-install

- include_tasks: config.yml
  tags:
    - system
    - networking
    - ssh
    - ssh-config

- include_tasks: known_hosts.yml
  tags:
    - system
    - networking
    - ssh
    - ssh-known-hosts

- include_tasks: service.yml
  tags:
    - system
    - networking
    - ssh
    - ssh-service
